name: llmini
channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.8
  - pip
  - numpy
  - tqdm
  - pytest
  - torch>=1.9.0
  - pandas
  - pyarrow
  - pip:
      - portalocker
      - tiktoken
      - -e ./external/wikitext