name: llmini
channels:
  - defaults
  - conda-forge
  - pytorch
  - pypi

dependencies:
  - python=3.11
  - pip
  - numpy
  - tqdm
  - pytest
  - torch=2.1
  - torchdata
  - torchtext
  - pip:
      - llmini==1.0.0
      - portalocker
      - tiktoken
      - -e ./external/wikitext